package com.mycloud.orchestratorservice.domain;

public enum OperationStepName {
    CHECK_CUSTOMER_QUOTA,
    CHECK_RESOURCE_ELIGIBILITY,
    CREATE_USER_TOKEN,
    LOAD_PROVIDER_CONFIGURATION,
    PROVIDER_LOGIN,
    PROVISION_RESOURCE,
    ASSIGN_PUBLIC_IP,
    COLLECT_RESOURCE_METADATA,
    REGISTER_MONITORING,
    COMMIT_QUOTA,
    REQUEST_BILLING,
    ROLLBACK_RESOURCE,
    RELEASE_QUOTA
}
